services:
  postgres:
    image: postgres:16
    container_name: gaman_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gaman_db
      POSTGRES_USER: gaman_user
      POSTGRES_PASSWORD: gaman_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gaman_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./storage:/app/storage
    depends_on:
      - postgres

volumes:
  postgres_data:
