"""Datos demo en memoria. Reemplazar por servicios reales cuando exista persistencia."""

from datetime import datetime, timedelta

_NOW = datetime(2026, 6, 18, 10, 30, 0)

CLIENTS = [
    {
        "id": 1,
        "nombre": "Muebles del Norte SA de CV",
        "rfc": "MNO850312AB1",
        "seccion": "21",
        "vendedor": "Carlos Mendoza",
    },
    {
        "id": 2,
        "nombre": "Distribuidora Hogar Plus",
        "rfc": "DHP920715CD2",
        "seccion": "14",
        "vendedor": "Ana Torres",
    },
    {
        "id": 3,
        "nombre": "Comercializadora Rivera",
        "rfc": "CRV880201EF3",
        "seccion": "21",
        "vendedor": "Luis Rivera",
    },
    {
        "id": 4,
        "nombre": "Grupo Muebles Express",
        "rfc": "GME950408GH4",
        "seccion": "08",
        "vendedor": "Patricia Gómez",
    },
    {
        "id": 5,
        "nombre": "Decoraciones Modernas",
        "rfc": "DMO870622IJ5",
        "seccion": "14",
        "vendedor": "Ana Torres",
    },
]

CASES = [
    {
        "id": 1,
        "folio": "REV-2026-0142",
        "cliente": "Muebles del Norte SA de CV",
        "rfc": "MNO850312AB1",
        "seccion": "21",
        "vendedor": "Carlos Mendoza",
        "tipo": "revision",
        "estado": "pendiente",
        "prioridad": "alta",
        "created_at": (_NOW - timedelta(hours=2)).isoformat(),
    },
    {
        "id": 2,
        "folio": "PED-2026-0087",
        "cliente": "Distribuidora Hogar Plus",
        "rfc": "DHP920715CD2",
        "seccion": "14",
        "vendedor": "Ana Torres",
        "tipo": "pedido",
        "estado": "en_compulsa",
        "prioridad": "media",
        "created_at": (_NOW - timedelta(hours=5)).isoformat(),
    },
    {
        "id": 3,
        "folio": "REF-2026-0031",
        "cliente": "Comercializadora Rivera",
        "rfc": "CRV880201EF3",
        "seccion": "21",
        "vendedor": "Luis Rivera",
        "tipo": "refinanciamiento",
        "estado": "en_revision",
        "prioridad": "alta",
        "created_at": (_NOW - timedelta(days=1)).isoformat(),
    },
    {
        "id": 4,
        "folio": "SAL-2026-0056",
        "cliente": "Grupo Muebles Express",
        "rfc": "GME950408GH4",
        "seccion": "08",
        "vendedor": "Patricia Gómez",
        "tipo": "saldo",
        "estado": "diferencia_detectada",
        "prioridad": "alta",
        "created_at": (_NOW - timedelta(days=1, hours=3)).isoformat(),
    },
    {
        "id": 5,
        "folio": "REV-2026-0143",
        "cliente": "Decoraciones Modernas",
        "rfc": "DMO870622IJ5",
        "seccion": "14",
        "vendedor": "Ana Torres",
        "tipo": "revision",
        "estado": "autorizado",
        "prioridad": "baja",
        "created_at": (_NOW - timedelta(days=2)).isoformat(),
    },
    {
        "id": 6,
        "folio": "PED-2026-0088",
        "cliente": "Muebles del Norte SA de CV",
        "rfc": "MNO850312AB1",
        "seccion": "21",
        "vendedor": "Carlos Mendoza",
        "tipo": "pedido",
        "estado": "pendiente_documentos",
        "prioridad": "media",
        "created_at": (_NOW - timedelta(days=2, hours=4)).isoformat(),
    },
    {
        "id": 7,
        "folio": "REF-2026-0032",
        "cliente": "Distribuidora Hogar Plus",
        "rfc": "DHP920715CD2",
        "seccion": "14",
        "vendedor": "Ana Torres",
        "tipo": "refinanciamiento",
        "estado": "aprobado",
        "prioridad": "baja",
        "created_at": (_NOW - timedelta(days=3)).isoformat(),
    },
    {
        "id": 8,
        "folio": "SAL-2026-0057",
        "cliente": "Comercializadora Rivera",
        "rfc": "CRV880201EF3",
        "seccion": "21",
        "vendedor": "Luis Rivera",
        "tipo": "saldo",
        "estado": "conciliado",
        "prioridad": "baja",
        "created_at": (_NOW - timedelta(days=4)).isoformat(),
    },
]

TALONES = [
    {
        "id": 1,
        "folio": "REV-2026-0142",
        "cliente": "Muebles del Norte SA de CV",
        "rfc": "MNO850312AB1",
        "seccion": "21",
        "vendedor": "Carlos Mendoza",
        "descuento_actual": 12.0,
        "descuento_nuevo": 18.5,
        "venta_posible": 245_800.00,
        "estado": "pendiente",
    },
    {
        "id": 2,
        "folio": "REV-2026-0143",
        "cliente": "Decoraciones Modernas",
        "rfc": "DMO870622IJ5",
        "seccion": "14",
        "vendedor": "Ana Torres",
        "descuento_actual": 10.0,
        "descuento_nuevo": 15.0,
        "venta_posible": 89_450.00,
        "estado": "autorizado",
    },
    {
        "id": 3,
        "folio": "REV-2026-0144",
        "cliente": "Grupo Muebles Express",
        "rfc": "GME950408GH4",
        "seccion": "08",
        "vendedor": "Patricia Gómez",
        "descuento_actual": 8.0,
        "descuento_nuevo": 14.0,
        "venta_posible": 156_200.00,
        "estado": "en_revision",
    },
    {
        "id": 4,
        "folio": "REV-2026-0145",
        "cliente": "Comercializadora Rivera",
        "rfc": "CRV880201EF3",
        "seccion": "21",
        "vendedor": "Luis Rivera",
        "descuento_actual": 15.0,
        "descuento_nuevo": 20.0,
        "venta_posible": 312_750.00,
        "estado": "pendiente",
    },
]

PEDIDOS = [
    {
        "id": 1,
        "folio": "PED-2026-0087",
        "cliente": "Distribuidora Hogar Plus",
        "tipo_venta": "contado",
        "vendedor": "Ana Torres",
        "documentos": ["orden_compra", "identificacion"],
        "estado": "en_compulsa",
    },
    {
        "id": 2,
        "folio": "PED-2026-0088",
        "cliente": "Muebles del Norte SA de CV",
        "tipo_venta": "credito",
        "vendedor": "Carlos Mendoza",
        "documentos": ["orden_compra"],
        "estado": "pendiente_documentos",
    },
    {
        "id": 3,
        "folio": "PED-2026-0089",
        "cliente": "Grupo Muebles Express",
        "tipo_venta": "contado",
        "vendedor": "Patricia Gómez",
        "documentos": ["orden_compra", "identificacion", "comprobante_domicilio"],
        "estado": "autorizado",
    },
    {
        "id": 4,
        "folio": "PED-2026-0090",
        "cliente": "Decoraciones Modernas",
        "tipo_venta": "credito",
        "vendedor": "Ana Torres",
        "documentos": ["orden_compra", "identificacion"],
        "estado": "en_compulsa",
    },
    {
        "id": 5,
        "folio": "PED-2026-0091",
        "cliente": "Comercializadora Rivera",
        "tipo_venta": "contado",
        "vendedor": "Luis Rivera",
        "documentos": ["orden_compra", "identificacion", "referencias"],
        "estado": "entregado",
    },
]

REFINANCIAMIENTOS = [
    {
        "id": 1,
        "cliente": "Comercializadora Rivera",
        "venta_original": "VTA-2024-1892",
        "saldo": 48_500.00,
        "pagado": 32_100.00,
        "porcentaje_pagado": 66.2,
        "elegible": True,
        "estado": "en_revision",
    },
    {
        "id": 2,
        "cliente": "Distribuidora Hogar Plus",
        "venta_original": "VTA-2023-1456",
        "saldo": 22_800.00,
        "pagado": 22_800.00,
        "porcentaje_pagado": 100.0,
        "elegible": True,
        "estado": "aprobado",
    },
    {
        "id": 3,
        "cliente": "Muebles del Norte SA de CV",
        "venta_original": "VTA-2025-0312",
        "saldo": 95_200.00,
        "pagado": 28_560.00,
        "porcentaje_pagado": 30.0,
        "elegible": False,
        "estado": "no_elegible",
    },
    {
        "id": 4,
        "cliente": "Grupo Muebles Express",
        "venta_original": "VTA-2024-2103",
        "saldo": 15_400.00,
        "pagado": 12_320.00,
        "porcentaje_pagado": 80.0,
        "elegible": True,
        "estado": "pendiente",
    },
]

SALDOS = [
    {
        "id": 1,
        "factura": "FAC-2026-4521",
        "cliente": "Grupo Muebles Express",
        "saldo_sistema": 18_750.00,
        "saldo_calculado": 19_125.00,
        "diferencia": 375.00,
        "estado": "diferencia_detectada",
    },
    {
        "id": 2,
        "factura": "FAC-2026-4518",
        "cliente": "Muebles del Norte SA de CV",
        "saldo_sistema": 42_300.00,
        "saldo_calculado": 42_300.00,
        "diferencia": 0.0,
        "estado": "conciliado",
    },
    {
        "id": 3,
        "factura": "FAC-2026-4509",
        "cliente": "Distribuidora Hogar Plus",
        "saldo_sistema": 8_920.00,
        "saldo_calculado": 9_180.00,
        "diferencia": 260.00,
        "estado": "diferencia_detectada",
    },
    {
        "id": 4,
        "factura": "FAC-2026-4495",
        "cliente": "Comercializadora Rivera",
        "saldo_sistema": 31_500.00,
        "saldo_calculado": 31_500.00,
        "diferencia": 0.0,
        "estado": "conciliado",
    },
    {
        "id": 5,
        "factura": "FAC-2026-4487",
        "cliente": "Decoraciones Modernas",
        "saldo_sistema": 5_640.00,
        "saldo_calculado": 5_890.00,
        "diferencia": 250.00,
        "estado": "en_revision",
    },
]

ACTIVITY = [
    {
        "id": 1,
        "tipo": "revision",
        "descripcion": "Nuevo talón REV-2026-0142 registrado para revisión",
        "usuario": "Carlos Mendoza",
        "timestamp": (_NOW - timedelta(hours=2)).isoformat(),
    },
    {
        "id": 2,
        "tipo": "pedido",
        "descripcion": "Pedido PED-2026-0087 enviado a compulsa",
        "usuario": "Ana Torres",
        "timestamp": (_NOW - timedelta(hours=4)).isoformat(),
    },
    {
        "id": 3,
        "tipo": "autorizacion",
        "descripcion": "Descuento autorizado en REV-2026-0143",
        "usuario": "Gerencia",
        "timestamp": (_NOW - timedelta(hours=6)).isoformat(),
    },
    {
        "id": 4,
        "tipo": "saldo",
        "descripcion": "Diferencia detectada en FAC-2026-4521",
        "usuario": "Sistema",
        "timestamp": (_NOW - timedelta(hours=8)).isoformat(),
    },
    {
        "id": 5,
        "tipo": "refinanciamiento",
        "descripcion": "Solicitud REF-2026-0031 en revisión",
        "usuario": "Luis Rivera",
        "timestamp": (_NOW - timedelta(days=1)).isoformat(),
    },
]

DOCUMENTS = [
    {
        "id": 1,
        "nombre": "Orden de compra PED-2026-0087.pdf",
        "tipo": "orden_compra",
        "cliente": "Distribuidora Hogar Plus",
        "folio": "PED-2026-0087",
        "uploaded_at": (_NOW - timedelta(hours=3)).isoformat(),
    },
    {
        "id": 2,
        "nombre": "Identificación MNO850312AB1.pdf",
        "tipo": "identificacion",
        "cliente": "Muebles del Norte SA de CV",
        "folio": "PED-2026-0088",
        "uploaded_at": (_NOW - timedelta(hours=5)).isoformat(),
    },
    {
        "id": 3,
        "nombre": "Talón REV-2026-0142.xlsx",
        "tipo": "talon",
        "cliente": "Muebles del Norte SA de CV",
        "folio": "REV-2026-0142",
        "uploaded_at": (_NOW - timedelta(hours=2)).isoformat(),
    },
    {
        "id": 4,
        "nombre": "Estado de cuenta CRV880201EF3.pdf",
        "tipo": "estado_cuenta",
        "cliente": "Comercializadora Rivera",
        "folio": "REF-2026-0031",
        "uploaded_at": (_NOW - timedelta(days=1)).isoformat(),
    },
]